module.exports = exports = {
  "Achelousaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/8/8b/Achelousaurus_dinosaur.png",
    "http://upload.wikimedia.org/wikipedia/commons/0/0e/Achelousaurus_BW.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/e/e6/Achelousaurus_horneri_BW.jpg",
  ],
  "Acrocanthosaurus": [
    "http://fc01.deviantart.net/fs70/i/2012/012/e/0/acrocanthosaurus_by_fukheelys-d4m38ln.jpg",
    "https://c1.staticflickr.com/5/4077/4851489018_cc2f08202c_b.jpg",
    "https://farm4.staticflickr.com/3271/2313044336_1b46c63c7d_o.jpg",
  ],
  "Aerosteon": [
    "http://upload.wikimedia.org/wikipedia/commons/a/a5/Carcharodontosaurus_BW.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/d/d7/Triceratops-vs-T-Rex001.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/4/4f/Mapusaurus_BW.jpg",
  ],
  "Afrovenator": [
    "http://upload.wikimedia.org/wikipedia/commons/8/8a/Afrovenator_mount.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/8/8b/Afrovenator_abakensis_dinosaur.png",
    "http://fc03.deviantart.net/fs71/i/2011/184/e/0/afrovenator_skelly_four_by_algoroth-d3kvfjp.jpg",
  ],
  "Albertosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/8/87/Albertosaurus.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/e/e6/Drumheller_150.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/a2/Albertosaurus_sculpture.jpg",
  ],
  "Alectrosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/a/ab/Appalachiosaurus_montgomeriensis.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/2/23/Appalachiosaurus_arms.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/3/36/Daspletosaurus_FMNH.jpg",
  ],
  "Allosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/5/51/Allosaurus_BW.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/3/3a/Allosaurus_SDNHM.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/5/51/Allosaurus_BW.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/9/9f/Allosaurus_in_Baltow_20060916_1500.jpg",
    "http://i.huffpost.com/gen/1151138/images/o-ALLOSAURUS-FEEDING-facebook.jpg",
  ],
  "Amargasaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/7/78/Amargasaurus,_DinoPark_Bratislava.JPG",
    "http://upload.wikimedia.org/wikipedia/commons/d/d0/Amargasaurus1_Melb_Museum_email.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/1/1b/Amargasaurus.jpg",
  ],
  "Anatosaurus": [
    "http://www.huntsearch.gla.ac.uk/zooimages/104025.JPG",
    "http://coloriages.dessins.free.fr/dessins/dessin%20dinosaure%20anatosaurus.jpg",
    "http://mikeingreensboro.com/IMG/IMGDEC2012/IMG_0775038.JPG",
  ],
  "Ankylosaurus": [
    "http://www.dinosaurfarm.com/wp-content/uploads/2013/11/Ankylosaurus-Papo.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/2/22/Ankylozaur_%28Ankylosaurus%29_-_JuraPark_Baltow_%281%29.JPG",
    "http://ayay.co.uk/backgrounds/dinosaurs/armoured/ankylosaurus.jpg",
  ],
  "Apatosaurus": [
    "http://images.fineartamerica.com/images-medium-large/apatosaurus-excelsus-a-prehistoric-era-sergey-krasovskiy.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/3/3a/Louisae.jpg",
    "http://images.fineartamerica.com/images-medium-large/apatosaurus-william-francis-phillipps.jpg",
  ],
  "Archaeopteryx": [
    "http://i.huffpost.com/gen/1458797/images/o-ARCHAEOPTERYX-facebook.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/e/e8/Archaeopteryx_fossil.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/7/73/Archaeopteryx_bavarica_Detail.jpg",
  ],
  "Argentinosaurus": [
    "http://dinosaurussen.weebly.com/uploads/1/1/2/9/11297522/8336363_orig.jpg",
    "http://res.cloudinary.com/dk-find-out/image/upload/q_80,w_1440/Argentinosaurus_HiRes_zrnqrq.jpg",
    "http://prehlife.weebly.com/uploads/2/2/0/8/22089980/194413227_orig.png?483",
  ],
  "Atlasaurus": [
    "http://www.renderosity.com/mod/gallery/media/folder_214/display_2132880.jpg",
    "http://www.thefossilforum.com/uploads/monthly_03_2015/post-2399-0-51102200-1425653027.jpg",
    "http://fc05.deviantart.net/fs70/i/2013/280/e/1/whale_of_a_tail_by_qilong-d6po0zi.png",
  ],
  "Baryonyx": [
    "http://fc09.deviantart.net/fs71/i/2013/297/4/9/baryonyx_by_baryonyx_walkeri-d6ro8h3.jpg",
    "http://static.guim.co.uk/sys-images/Guardian/Pix/pictures/2009/2/7/1234015672079/Baryonyx-dinosaur-004.jpg",
    "http://img2.wikia.nocookie.net/__cb20131024144124/dinosaurs/images/9/98/Baryonyx_by_frank_lode-d4q4382.jpg",
  ],
  "Beipiaosaurus": [
    "http://cdn.dinosaur-world.com/feathered_dinosaurs/species/beipiaosaurus_inexpectatus.gif?rewrite=true",
    "http://img2.wikia.nocookie.net/__cb20130724191743/dinosaurs/images/1/13/Beipiaosaurus.jpg",
    "http://www.rareresource.com/images/beipiaosaurus.jpg",
  ],
  "Belemnites": [
    "http://upload.wikimedia.org/wikipedia/commons/3/33/BelemniteDB2.jpg",
    "https://ferrebeekeeper.files.wordpress.com/2012/03/belemnite.png",
    "http://museumvictoria.com.au/pages/17138/imagegallery/1pic-43017.jpg",
  ],
  "Bothriolepis": [
    "http://www.mun.ca/biology/scarr/Bothriolepis.jpg",
    "http://www.nhm.ac.uk/hosted_sites/paleonet/vop/3Dpaleo/Bothriolepis.jpg",
    "http://macroevolution.narod.ru/vertebrates/bothriolepis2.jpg",
  ],
  "Brachiosaurus": [
    "http://static.comicvine.com/uploads/original/11119/111192788/4241681-5056537572-brach.jpg",
    "http://vignette4.wikia.nocookie.net/walkingwith/images/2/20/WWD1x2_Brachiosaurus.jpg/revision/latest?cb=20130622091458",
    "http://upload.wikimedia.org/wikipedia/commons/0/07/Dinosaurios_Park,_Brachiosaurus_young.JPG",
    "http://www.rareresource.com/photos/dinosaur-gallery/brachiosaurus3.jpg",
  ],
  "Brontosaurus": [
    "http://www.unmuseum.org/apat2.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/3/3e/Pasta-Brontosaurus.jpg",
    "http://www.todayifoundout.com/wp-content/uploads/2011/11/brontosaurus.jpg",
    "http://www.regaltribune.com/wp-content/uploads/2015/04/The-Brontosaurus-finally-gets-its-own-genus.jpg",
    "https://cdn1.vox-cdn.com/thumbor/8KixlxskAdTvqyI2JyXC-CGJPqQ=/cdn0.vox-cdn.com/uploads/chorus_asset/file/3581204/Brontosaurus_Copyright_DavideBonadonna-1.0.jpg",
    "http://www.worldreportnow.com/wp-content/uploads/2015/04/brontosaur.jpeg",
    "http://www.zastavki.com/pictures/originals/2014/_Brontosaurus_Tyrannosaurus_attack_082053_.jpg"
  ],
  "Bryozoaires": [
    "http://www.webplongee.com/assets/galleries/164/reteporella-grimaldii.jpg",
    "http://www2.ac-lyon.fr/enseigne/biologie/photossql/images/Reteporella_g.jpg",
    "http://manu-plongee.pagesperso-orange.fr/bio/Bryozoaires/Bryozoaires%20Frondipora%20verrucosa%20-%20Aedonella%20calveti-%20Pentapora%20foliacea.jpg",
  ],
  "Buitreraptor": [
    "http://img1.wikia.nocookie.net/__cb20141119232923/dinosaurs/images/c/c2/Buitreraptor-dinosaurs-28667916-796-392.png",
    "http://upload.wikimedia.org/wikipedia/commons/2/29/Buitreraptor-Deinonychus.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/9/94/Buitreraptor.jpg",
  ],
  "Camarasaurus": [
    "http://img3.wikia.nocookie.net/__cb20140716002911/dinosaurs/images/1/1e/Camarasaurus_sauropod.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/f/f6/Camarasaurs1.jpg",
    "http://www.popartdecoration.com/projects/camarasaurus-dinosaur-2438-2900-2.jpg",
  ],
  "Cambrian": [
    "http://baccyflap.com/blog/2007/img2007/cambriansea.jpg",
    "http://www.wired.com/images_blogs/wiredscience/2011/12/Anomalocaris-nature.jpg",
    "http://ocean.si.edu/sites/default/files/styles/colorbox_full/public/photos/602P01G01Burgess_Shalew.jpg?itok=F6dRsgYn",
  ],
  "Camptosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/1/1d/Camptosaurus.jpg",
    "http://www.beutelwolf.martin-skerhut.de/wp-content/uploads/2014/03/Camptosaurus-dispar.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/7/79/Camptosaurus_aphanoecetes_-_IMG_0673.jpg",
  ],
  "Carboniferous": [
    "http://th07.deviantart.net/fs71/PRE/i/2013/262/7/8/carboniferous_by_jiestat-d6n0723.jpg",
    "https://spinokingtech104.files.wordpress.com/2013/02/amphibian_gang.jpg",
    "https://s-media-cache-ak0.pinimg.com/originals/4b/9c/e9/4b9ce943900fad5033c83eede6fa3d23.jpg",
  ],
  "Carcharodontosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/a/a5/Carcharodontosaurus_BW.jpg",
    "http://dinosaurios.org/wp-content/uploads/2013/08/carcharodontosaurus.jpg",
    "http://www.wikidino.com/wp-content/uploads/Carcharodontosaurus-Brett-Booth-3.jpg",
  ],
  "Carnosaur": [
    "http://fc05.deviantart.net/fs10/i/2006/105/d/5/The_clearing_by_Carnosaur.jpg",
    "http://fc06.deviantart.net/fs71/i/2013/353/1/5/thrasher__by_carnosaur-d6yhvzw.jpg",
    "http://www.rareresource.com/images/dinosaurs/carnotauros.png",
    "http://img1.wikia.nocookie.net/__cb20140912201850/disney/images/6/69/Carnotaurus.jpg",
  ],
  "Cearadactylus": [
    "http://upload.wikimedia.org/wikipedia/commons/5/5d/Cearadaktyl_%28Cearadactylus%29_-_JuraPark_Baltow_%282%29.JPG",
    "http://dic.academic.ru/pictures/wiki/files/67/Cearadactylus_model.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/f/f3/Cearadaktyl_%28Cearadactylus%29_-_JuraPark_Baltow_%284%29.JPG",
  ],
  "Ceratopsia": [
    "http://www.de-aarde.com/wp-content/uploads/2011/02/Ceratopsia.jpg",
    "http://images.fineartamerica.com/images-medium-large/medusaceratops-lokii-a-prehistoric-era-sergey-krasovskiy.jpg",
    "http://animalreader.ru/wp-content/uploads/2014/09/Ceratopsia8.jpg",
  ],
  "Charonosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/8/86/Charonosaurus-v3.jpg",
    "http://media.moddb.com/images/mods/1/22/21590/Charono.png",
    "http://img2.wikia.nocookie.net/__cb20140204235505/dinosaurs/images/a/a2/Charonosaurus-Enchanters-Blood.jpg",
  ],
  "Chasmosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/1/1f/Chasmosaurus_BW.jpg",
    "http://dinosaurs.afly.ru/ii/c/chasmosaurus-1.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/ac/Royal_Tyrell_Chasmosaurus_russelli.jpg",
  ],
  "Chirostenotes": [
    "http://vignette1.wikia.nocookie.net/walkingwith/images/9/98/Chirostenotes.png/revision/latest?cb=20130913041547",
    "http://www.insidethelinesvsfx.com/section_images/scad/733-chiro/final1.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Chirostenot_%28Chirostenotes%29_-_JuraPark_Baltow_%282%29.JPG/1280px-Chirostenot_%28Chirostenotes%29_-_JuraPark_Baltow_%282%29.JPG",
  ],
  "Coelacanth": [
    "http://newsdesk.si.edu/sites/default/files/photos/nmnh_coelacanth.jpg",
    "http://vertebrates.si.edu/fishes/coelacanth/comoros_coelacanth_USNM.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/e/e4/Coelacanth_model,_Devonian_-_Houston_Museum_of_Natural_Science_-_DSC01709.JPG",
  ],
  "Coelophysis": [
    "http://res.cloudinary.com/dk-find-out/image/upload/q_80,w_1440/Coelophysis_layers_qrvgwy.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/1/1a/Coelophysis_Animatronics_model_NHM2.jpg",
    "http://www.cmstudio.com/image/Coelophysis036.jpg",
  ],
  "Coelurosaur": [
    "http://vignette2.wikia.nocookie.net/walkingpedia/images/2/2f/CoelurosaurInfobox.jpg/revision/latest?cb=20140323113529",
    "http://upload.wikimedia.org/wikipedia/commons/8/84/Zuni_Coelurosaur.jpg",
    "http://img1.wikia.nocookie.net/__cb20100509174911/entirelydinosaur/images/1/1b/Guanlong.jpg",
  ],
  "Compsognathus": [
    "http://www.wikidino.com/wp-content/uploads/Compsognathus-Peter-Minister.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/c/cd/Compsognathus_longipes_skeleton_reconstruction_munich.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/c/c4/Compsognathus_BW.jpg",
  ],
  "Concavenator": [
    "http://fc01.deviantart.net/fs70/i/2012/209/1/4/concavenator_by_baryonyx_walkeri-d5904vr.jpg",
    "http://fc06.deviantart.net/fs70/f/2011/173/f/e/fe8dd1fc7b5895af4d2ac502971f90be-d3jolta.jpg",
    "http://fc07.deviantart.net/fs70/i/2011/131/f/3/concavenator_figth_by_jelsin-d3g3uiq.jpg",
  ],
  "Corythosaur": [
    "http://upload.wikimedia.org/wikipedia/commons/7/7a/Corythosaurus_casuarius,_Dinosaur_Provincial_Park,_Alberta,_Canada,_Late_Cretaceous_-_Royal_Ontario_Museum_-_DSC00023.JPG",
    "http://img1.findthebest.com/sites/default/files/426/media/images/Corythosaurus_1126281.jpg",
    "http://fc07.deviantart.net/fs71/f/2012/341/0/7/075b10ffa2dc5c6bc09f49787d016f99-d5n373h.jpg",
  ],
  "Cretaceous Marine": [
    "http://collections.mnh.si.edu/media/?i=10484587",
    "http://www.karencarr.com/phpThumb.php?src=/auto_image/Karen_Carr_Cretaceous_Marine_Environment_mosasaur_detail.jpg",
    "http://www.karencarr.com/phpThumb.php?src=/auto_image/Karen_Carr_Cretaceous_Marine_Environment.jpg",
  ],
  "Cretoxyrhina Clidastes": [
    "https://s-media-cache-ak0.pinimg.com/736x/da/b7/21/dab721866d9761c208f966b02235be9d.jpg",
    "http://fc06.deviantart.net/fs70/i/2013/209/f/d/tylosaurus_riapaeus_by_malvit-d6fel9a.jpg",
    "http://img.xooimage.com/files108/2/a/6/beneath_the_surfa...-d4h5chy-46859dc.png",
  ],
  "Cryolophosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/d/d4/Cryolophosaurus_in_Japan.jpg",
    "http://www.urbanmoms.ca/the_cultured_pearl/Cryolophosaurus.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/4/4c/Augustana_College_Cryolophosaurus.JPG",
  ],
  "Cryptoclidus": [
    "http://forum.zbrush.fr/gallery/11821_26_03_12_12_50_26.jpeg",
    "http://upload.wikimedia.org/wikipedia/commons/e/ea/Cryptoclidus_eurymerus_Tubingen.JPG",
    "http://plesiosauria.com/images/photographs/cryptoclidus_glasgow.jpg",
  ],
  "Daspletosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/a/a8/Chicago_Field_Museum_-_Daspletosaurus.jpg",
    "http://img4.wikia.nocookie.net/__cb20120703210700/dinosaurs/images/a/a7/Daspletosaurus.jpg",
    "http://www.cmstudio.com/image/Daspletosaurus047.jpg",
  ],
  "Deinonychus": [
    "http://upload.wikimedia.org/wikipedia/commons/e/ed/FMNH_Deinonychus.JPG",
    "https://www.q-files.com/images/pages/galleries/598/deinonychus-1.jpg",
    "http://dinosaurios.org/wp-content/uploads/2013/08/deinonychus-1.jpg",
  ],
  "Dilong": [
    "http://th09.deviantart.net/fs71/PRE/i/2011/355/3/9/dilong_by_atrox1-d4i6do5.jpg",
    "http://fc07.deviantart.net/fs7/i/2005/262/a/d/Dilong_and_Sinornithosaurus_2_by_Ferahgo_the_Assassin.jpg",
    "http://41.media.tumblr.com/tumblr_loy386PWCU1qa1853o1_1280.jpg",
  ],
  "Dilophosaurus": [
    "http://www.dinosaurfarm.com/wp-content/uploads/2014/07/Dilophosaurus-2014-Papo.jpg",
    "http://preview.turbosquid.com/Preview/2014/05/17__23_40_00/126981_Dilophosaurus_Pose_1_007.jpgdabaa394-064a-4eeb-b987-c5068658f9dcOriginal.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/1/12/DilophosaurusROM1.JPG",
  ],
  "Dimetrodon": [
    "http://upload.wikimedia.org/wikipedia/commons/8/82/Dimetrodon_skeleton.jpg",
    "http://www.nhm.ac.uk/natureplus/servlet/JiveServlet/download/2585-1132/dimetrodon.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/4/46/Dimetrodon_Field_Museum.jpg",
  ],
  "Dimorphodon": [
    "http://fc00.deviantart.net/fs48/f/2009/197/6/c/Dimorphodon_by_sash4all.jpg",
    "https://library.creativecow.net/articles/kaufman_debra/Flying-Monsters-3D/assets/Flying-Monsters-3D-with-David-Attenborough-Dimorphodon.jpg",
    "https://library.creativecow.net/articles/kaufman_debra/Flying-Monsters-3D/assets/DIMORPHODON_comp_v2.jpg",
  ],
  "Diplodocus": [
    "http://www.3dartistonline.com/users/1358/thm1024/1361532355_diplo-b.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/c/cf/Diplodocus_%28replica%29.001_-_London.JPG",
    "http://vignette1.wikia.nocookie.net/walkingwith/images/3/34/WWDBook_Diplodocus.jpg/revision/latest?cb=20131123073046",
  ],
  "Dromeosaur": [
    "http://fc08.deviantart.net/fs71/f/2012/170/a/8/sign_of_the_dromaeosaur_by_ewilloughby-d544mxj.jpg",
    "http://blenderartists.org/forum/attachment.php?attachmentid=176685&d=1332977181",
    "http://upload.wikimedia.org/wikipedia/commons/7/78/Dromaeosaur.jpg",
  ],
  "Dunkleosteus": [
    "http://fc00.deviantart.net/fs70/i/2012/282/6/1/dunkleosteus_by_fel05-d5hb2l4.jpg",
    "http://www.uneed2know.eu/general-photos/articles/dunkleosteus_large.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/5/5b/Dunkleosteus_profile.jpg",
  ],
  "Edmontonia": [
    "http://upload.wikimedia.org/wikipedia/commons/1/19/Edmontonia_mount.jpg",
    "http://vignette3.wikia.nocookie.net/walkingwith/images/f/f5/Imgrese.jpg/revision/latest?cb=20130624173052",
    "http://upload.wikimedia.org/wikipedia/commons/6/6a/Edmontonia_half.jpg",
  ],
  "Einiosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/c/cf/Einiosaurus_skull.jpg",
    "http://fc09.deviantart.net/fs71/i/2013/084/2/f/einiosaurus__15__by_wolverine041269-d5z77tf.png",
    "http://www.arcadiastreet.com/cgvistas/earth/03_mesozoic/images/einiosaurus_portrait_800.jpg",
  ],
  "Elasmosaurus": [
    "http://fc07.deviantart.net/fs70/f/2013/317/1/0/26_by_paleoguy-d6u56mh.jpg",
    "http://images.fineartamerica.com/images-medium-large/elasmosaurus-platyurus-a-prehistoric-sergey-krasovskiy.jpg",
    "http://images5.fanpop.com/image/photos/28200000/Elasmosaurus-dinosaurs-28286825-1000-423.jpg",
  ],
  "Euoplocephalus": [
    "http://upload.wikimedia.org/wikipedia/commons/3/3b/Euoplocephalus_tutus.jpg",
    "http://www.boundless-creativity.com/wp-content/uploads/2013/09/14EuoplocephalusInWoodsBC13lg.jpg",
    "https://archosaurmusings.files.wordpress.com/2012/04/ankylo351.jpg",
  ],
  "Formacionmorrison": [
    "http://maxillaandmandible.com/wp-content/uploads/2013/07/sb-actual.png",
    "https://geofrikphotos.files.wordpress.com/2013/02/diplodocus-1.jpg?w=968&h=809",
    "http://phenomena.nationalgeographic.com/files/2012/12/howe-quarry-restoration-990x659.jpg",
  ],
  "Futalongkosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/3/3d/%27Futalognkosaurus.JPG",
    "http://i255.photobucket.com/albums/hh141/doramu13/Futalognkosaurus-1.jpg",
    "http://happ.ly/interactives/explore_Futalognkosaurus/i/Futalognkosaurus.jpg",
  ],
  "Giganotosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/b/bd/Giganotosaurus.jpg",
    "http://fc02.deviantart.net/fs71/i/2010/140/b/c/giganotosaurus_by_Gonzalezaurus.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/f/f2/Giganotosaurus_carolinii_DSC_2949.jpg",
  ],
  "Gorgosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/b/be/Sharp_naturalhistory_1920_Gorgosaurus.jpg",
    "http://fc01.deviantart.net/fs70/i/2011/120/b/7/gorgosaurus_2_by_baryonyx_walkeri-d3f8mbx.jpg",
    "http://fc04.deviantart.net/fs12/f/2012/345/2/8/2893c2b90c578797aa95f9ee71dda361-domyhm.jpg",
  ],
  "Hadrosaurus": [
    "https://upload.wikimedia.org/wikipedia/commons/2/2a/Hadrosaurus_reconstruction.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/a9/Hadrosaurus_skull.jpg",
    "http://matchbin-assets.s3.amazonaws.com/public/sites/383/assets/EREU_07secdinosaur14_1.jpg",
  ],
  "Helicoprion": [
    "http://www.karencarr.com/phpThumb.php?src=/auto_image/Heliocoprian.jpg",
    "http://41.media.tumblr.com/tumblr_lo4qng97hp1qdjdf3o1_1280.jpg",
    "http://images.fineartamerica.com/images-medium-large/helicoprion-with-ammonites-christian-darkin.jpg",
  ],
  "Huaxiagnathus": [
    "http://upload.wikimedia.org/wikipedia/commons/4/4e/Huaxiagnathus_orientalis.JPG",
    "http://40.media.tumblr.com/fe5fd8bc9ac5f47dbc0850f3fa679afb/tumblr_nd5khzSQ6A1sxjia7o3_1280.jpg",
    "http://www.oldearth.org/curriculum/dinosaur/Compsognathus_BW.jpg",
  ],
  "Huayangosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/2/2c/Fossil_Kentrosaurus_aethiopicus_in_Museum_f%C3%BCr_Naturkunde_Berlin_001.JPG",
    "http://fc00.deviantart.net/fs70/i/2013/109/5/1/kentrosaurus_encounter_by_fred5612-d629594.png",
    "http://upload.wikimedia.org/wikipedia/commons/2/24/Huayangosaurus_taibaii_20050707_07.jpg",
  ],
  "Hypacrosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/1/10/Hypacrosaurus_skeleton.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/c/cb/Tyrrell_Hypacrosaurus.jpg",
    "http://quietmotion.com/Portals/1/LiveContent/1360/Images/Hypacrosaurus.jpg",
  ],
  "Ichthyosaur": [
    "http://upload.wikimedia.org/wikipedia/commons/c/c5/Ichthyosaur_mounted_skeleton.jpg",
    "http://fc07.deviantart.net/fs71/i/2013/234/b/8/ichthyosaur_group_by_esthervanhulsen-d6j2rge.jpg",
    "http://fc02.deviantart.net/fs71/i/2013/234/4/1/ichthyosaur_love_by_esthervanhulsen-d6j7evr.jpg",
  ],
  "Ichtyostega": [
    "http://upload.wikimedia.org/wikipedia/commons/d/d7/Skeleton_of_Ichthyostega.JPG",
    "http://fc01.deviantart.net/fs29/f/2008/048/9/7/Ichthyostega_revisited_by_dustdevil.jpg",
    "http://facweb.furman.edu/~wworthen/bio440/evolweb/devonian/ichthy2.jpg",
  ],
  "Iguanodon": [
    "http://fr.academic.ru/pictures/frwiki/77/Mantellisaurus_atherfieldensis_Steveoc.jpg",
    "http://vignette2.wikia.nocookie.net/worldofprehistory/images/f/fc/Ig.jpg/revision/latest?cb=20120626132221",
    "http://upload.wikimedia.org/wikipedia/commons/5/50/Iguanodon_bernissartensis.jpg",
  ],
  "Jobaria": [
    "http://upload.wikimedia.org/wikipedia/commons/8/8e/Jobaria_and_Suchomimus.jpg",
    "http://www.makecnc.com/prodimages/Jobaria-scrollsaw-4axis-3axis-pattern-dinosaur-t46_1000.jpg",
    "https://svpow.files.wordpress.com/2011/03/brontomerus2.jpg",
  ],
  "Jurassic": [
    "http://upload.wikimedia.org/wikipedia/commons/1/1c/Europasaurus_holgeri_Scene_2.jpg",
    "http://www.jurassicquest.com/images/subpage_bg1b.jpg",
    "http://www.picgifs.com/wallpapers/movie-and-tv-shows/jurassic-park/wallpaper_jurasic-parc_animaatjes-15.jpg",
  ],
  "Kentrosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/2/2c/Fossil_Kentrosaurus_aethiopicus_in_Museum_f%C3%BCr_Naturkunde_Berlin_001.JPG",
    "http://th02.deviantart.net/fs70/PRE/i/2013/109/5/1/kentrosaurus_encounter_by_fred5612-d629594.png",
    "http://upload.wikimedia.org/wikipedia/commons/e/ec/Berlin_Naturkundemuseum_Dino_Eingangshalle.jpg",
  ],
  "Khaan": [
    "https://dinosaurpalaeo.files.wordpress.com/2011/09/1127.jpg",
    "http://www.rareresource.com/photos/Khaan.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/6/6e/Khaan.jpg",
  ],
  "Lacusovagus": [
    "https://archosaurmusings.files.wordpress.com/2010/11/dimoprh-model.jpg",
    "http://th01.deviantart.net/fs71/PRE/i/2013/081/8/2/lacusovagus_by_dyn0saur-d5yuzy5.png",
    "http://upload.wikimedia.org/wikipedia/commons/9/99/Lacusovagus_JWPhoto.JPG",
  ],
  "Lambeosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/a/af/Lambeosaurus_ROM.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/f/f7/Lambeosaurus_skeleton.jpg",
    "https://sauropedia.files.wordpress.com/2012/01/lambeosaurus.jpg",
  ],
  "Leptosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/c/c1/Leptosaurus_pulchellus.JPG",
    "http://fc00.deviantart.net/fs25/f/2008/148/5/3/Herrerasaurus_by_jupiterjenny.jpg",
    "http://kazkamen.cz/images/galerie/Lepto.jpg",
  ],
  "Lesothosaurus": [
    "http://www.rareresource.com/images/lesothosaurus.jpg",
    "http://images.nationalgeographic.com/wpf/media-live/photos/000/007/cache/lesothosaurus_777_600x450.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Lesothosaurus_ER670.JPG/220px-Lesothosaurus_ER670.JPG",
    "http://img3.wikia.nocookie.net/__cb20130625175854/dinosaurs/images/8/8c/Lesothosaurus-dinosaurs-28286649-630-379.jpg",
  ],
  "Lystrosaurus": [
    "http://de.academic.ru/pictures/dewiki/76/Lystrosaurus_murrayi.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/a5/Lystrosaurus_1.JPG",
    "http://40.media.tumblr.com/975911411f17173602babc8e7005b472/tumblr_mil3826BWV1rmeji6o1_r1_1280.jpg",
  ],
  "Majungatholus": [
    "http://www.oldearth.org/curriculum/dinosaur/majungasaurus.jpg",
    "http://www.rileytalk.com/majungatholus-male.png",
    "https://c1.staticflickr.com/7/6166/6230364256_7d765c043c_b.jpg",
    "http://www.prehistoria.piwko.pl/Obrazki/Majungatholus2.jpg",
    "http://vignette3.wikia.nocookie.net/jurassicfightclub/images/c/c7/Majungatholus.jpg/revision/latest?cb=20080924024043",
    "http://dinonews.net/images/dinos/majungatholus.jpg",
  ],
  "Makiakasaurus": [
    "http://images.fineartamerica.com/images-medium-large/the-mouth-of-masiakasaurus-pixeldust-studios.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/0/0d/Masiakosaurus_skull_FMNH.jpg",
    "https://paleoreplica.files.wordpress.com/2013/03/masiakasaurus-knopfleri.jpg",
  ],
  "Mamenchisaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/9/94/Sauropods.jpg",
    "http://th00.deviantart.net/fs71/PRE/i/2010/005/d/2/Mamenchisaurus_by_AshiRox.jpg",
    "http://th00.deviantart.net/fs71/PRE/i/2014/145/3/d/mamenchisaurus_by_atrox1-d6kg2m2.jpg",
  ],
  "Maniraptoraclaw": [
    "http://upload.wikimedia.org/wikipedia/commons/d/dd/Utahraptor_skeleton_NAMAL.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/5/5c/Allosaurus-fragilis-Klauen.JPG",
    "http://upload.wikimedia.org/wikipedia/commons/2/29/Buitreraptor-Deinonychus.jpg",
  ],
  "Methriorhynchus": [
    "http://upload.wikimedia.org/wikipedia/commons/c/c8/Metriorhynchus_jaekeli_-_Naturmuseum_Senckenberg_-_DSC02182.JPG",
    "http://upload.wikimedia.org/wikipedia/commons/9/95/Metriorhynchus_dubr1DB.jpg",
    "http://vignette1.wikia.nocookie.net/walkingwith/images/2/2d/SMBook_Metriorhynchus.jpg/revision/latest?cb=20131123073459",
  ],
  "Microraptor": [
    "http://fc09.deviantart.net/fs71/i/2012/335/d/8/microraptor_by_atrox1-d5mg5w9.jpg",
    "http://www.jsg.utexas.edu/news/files/07microraptor3.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/af/Microraptor_gui_holotype.png",
  ],
  "Minmi": [
    "http://upload.wikimedia.org/wikipedia/commons/a/a8/Minmi_paravertebra_dinosauria.png",
    "http://australianageofdinosaurs.com/resources/Dinosaurs/Aust_Dinos/Minmi_paravertebra/Minmi-aaodl.com.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/3/39/Minmi_model_Canberra_email.jpg",
    "http://www.qm.qld.gov.au/Find+out+about/Dinosaurs+and+Ancient+Life+of+Queensland/Dinosaurs/Eromanga+giants/~/media/9204B520608F4AC588EE2FA98866D4BE.ashx?h=154&w=399&as=1",
    "http://australianmuseum.net.au/uploads/images/7236/minmi_big.jpg",
  ],
  "Monolophosaurus": [
    "http://www.captmondo.com/weblog/uploaded_images/MonolophosaurusJiangiAttackingATuojiangosaurusMultispinus-PaleozoologicalMuseumOfChina-May23-08-757767.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/1/16/Monolophosaurus_skull.jpg",
    "http://fc03.deviantart.net/fs70/i/2013/163/6/5/monolophosaurus_by_sylxeriaguardian-d68r7s3.jpg",
  ],
  "Mosasaurus": [
    "http://www.jurassicworlduniverse.com/wordpress/wp-content/uploads/2014/11/mosasaurus3.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/a9/Mosasaurus_hoffmannii_-_skeleton.jpg",
    "http://vignette2.wikia.nocookie.net/dinosauralive/images/c/c4/Mosasaurus.jpg/revision/latest?cb=20130116153551",
  ],
  "Muttaburrasaurus": [
    "http://en.academic.ru/pictures/enwiki/77/Muttaburrasaurus_skull_aus.jpg",
    "http://fc06.deviantart.net/fs71/i/2010/049/a/0/muttaburrasaurus_by_ministerart.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/d/de/Muttaburrasaurus-skeleton-at-Queensland-Museum.jpg",
  ],
  "Nodosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/6/6d/Pinacosaurus.jpg",
    "http://static.spark.autodesk.com/2012/08/15__05_47_54/13631_Front0000.jpgec10f482-e30c-402f-bb94-b4e90e758e81Large.jpg",
    "http://www.nhm.ac.uk/resources/nature-online/life/dinosaurs/dino-directory/colour/src/Edmontonia.jpg",
  ],
  "Nyctosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/3/3f/Nyctosaurus_gracilis_1.JPG",
    "http://fc00.deviantart.net/fs71/f/2012/059/6/9/nyctosaurus_agravicilis_by_thomastapir-d4r8xbk.jpg",
    "http://en.academic.ru/pictures/enwiki/68/Dinosaurs_at_CMNH_49.JPG",
  ],
  "Ornithocherirus": [
    "http://www.dinosaurlive.com/connectwp/wp-content/uploads/akagallery/746/6856960750.jpg",
    "http://www.dinosaurlive.com/connectwp/wp-content/uploads/akagallery/746/7003075611.jpg",
    "i.ytimg.com/vi/6KenXFo7oxU/maxresdefault.jpg",
  ],
  "Ornithomimosaurus": [
    "http://phenomena.nationalgeographic.com/files/2013/01/struthiomimus-large-990x665.jpg",
    "http://www.redorbit.com/media/uploads/2004/10/66_fc108fed1fab09dee8e0700de20224bc.jpg",
    "https://archosaurmusings.files.wordpress.com/2010/02/dsc_0077.jpg",
  ],
  "Othiniela": [
    "http://upload.wikimedia.org/wikipedia/commons/2/24/Othnielia.png",
    "http://upload.wikimedia.org/wikipedia/commons/b/b7/Othnielia.jpg",
    "http://en.academic.ru/pictures/enwiki/70/Fighting_Othnielia.jpg",
  ],
  "Pachycephalosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/f/fe/Pachycephalosaurus_in_Japan.jpg",
    "http://dinosaurios.org/wp-content/uploads/2013/09/Pachycephalosaurus_FULL.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/c/c0/Pachycephalosaurus_RoyalOntarioMuseum.png",
  ],
  "Paralititan": [
    "https://svpow.files.wordpress.com/2013/09/chaos_gigantes_by_algoroth-d3ljhww.jpg",
    "http://vignette4.wikia.nocookie.net/bbcplanetdinosaur/images/d/d7/Paralatitan_1.png/revision/latest?cb=20111101202033",
    "http://img3.wikia.nocookie.net/__cb20130916003629/dinosauralive/images/9/97/Paralititan_4.png",
  ],
  "Parasaurolophus": [
    "http://upload.wikimedia.org/wikipedia/commons/1/14/Parasaurolophus_cyrtocristatus.jpg",
    "https://d1u1p2xjjiahg3.cloudfront.net/7c8bf628-e78b-460e-9239-a27f98bede8a_l.jpg",
    "http://mercanta.se/wp-content/plugins/rss-poster/cache/5fc62_Parasaurolophus-Before.jpg",
  ],
  "Patagosaurus": [
    "https://c1.staticflickr.com/3/2879/9920753895_c60ae94475_b.jpg",
    "http://www.temaiken.org.ar/files/items/imagenes/Foto%20dinosaurios%20%282%29.jpg",
    "https://s-media-cache-ak0.pinimg.com/736x/08/70/ae/0870aefb4bb6a823ea3a42a8f216d103.jpg",
  ],
  "Plateosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/9/99/Sellosaurus.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/9/93/Plateosaurus_Skelett_2.jpg",
    "http://fc08.deviantart.net/fs70/i/2014/107/7/a/plateosaurus_by_deskridge-d7euv1k.jpg",
  ],
  "Psittacosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/b/b7/Psittacosaurus_sibiricus_whole_BW.jpg",
    "http://images.fineartamerica.com/images-medium-large/psittacosaurus-mongoliensis-sergey-krasovskiy.jpg",
    "http://38.media.tumblr.com/4830a7a79b8edfdbcb2a7350cb8c4acf/tumblr_inline_nczmo7tyg91rx4yme.jpg",
    "http://fc00.deviantart.net/fs71/f/2013/021/d/6/d68e1ccb772866e398c5366922b8aded-d5saevy.jpg",
    "http://planetdi.startlogic.com/dinosaur_list/images/psittacosaurus_tm.gif",
  ],
  "Pteranodon": [
    "http://media.indiedb.com/images/games/1/13/12455/PTE_Render_00.jpg",
    "http://vignette3.wikia.nocookie.net/walkingwith/images/9/92/Pteranodon-WWD.jpg/revision/latest?cb=20130426144835",
    "http://plesiosauria.com/dinotoyimage/papo_pteranodon_head.jpg",
  ],
  "Pterodactyl": [
    "http://preview.turbosquid.com/Preview/2014/07/11__18_40_40/PterodactylPose1_38.jpgb3d12ea8-7546-4456-963b-2f218042cdf5Original.jpg",
    "http://fc00.deviantart.net/fs71/i/2012/179/d/f/baby_pterodactyl_by_fuvl-d556z1i.jpg",
    "http://martinjclemens.com/wp-content/uploads/2014/05/JPTLWPteranodon1.png",
  ],
  "Qantassaurus": [
    "http://www.redorbit.com/media/uploads/2004/10/0_3e49053d4371b8f8e282181e1c99ee7f.jpg",
    "http://home.alphalink.com.au/~dannj/qantcol.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Qantassaurus_sketch1.jpg/220px-Qantassaurus_sketch1.jpg",
    "http://fc05.deviantart.net/fs70/f/2012/225/1/4/qantassaurus_sparing_by_2195razielim-d5b0rc5.gif",
    "http://vignette3.wikia.nocookie.net/prehistrico/images/d/d0/Qantassaurus.jpg/revision/latest?cb=20140301193543&path-prefix=es",
  ],
  "Quetzalcoatlus": [
    "http://upload.wikimedia.org/wikipedia/commons/6/6b/Life_restoration_of_a_group_of_giant_azhdarchids,_Quetzalcoatlus_northropi,_foraging_on_a_Cretaceous_fern_prairie.png",
    "https://optimisticpainter.files.wordpress.com/2011/03/quetzalcoatlus_blog.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/ab/Quetzalcoatlus_1.JPG",
  ],
  "Rajasarus": [
    "http://www.sciencekids.co.nz/images/pictures/dinosaurs/rajasaurus.jpg",
    "http://static.panoramio.com/photos/large/55759504.jpg",
    "http://i.imgur.com/qSOPmhs.jpg",
  ],
  "Raptorex": [
    "http://mjfowler.weebly.com/uploads/2/4/0/9/24097146/1465554_orig.jpg",
    "https://archosaurmusings.files.wordpress.com/2011/09/img_4821.jpg",
    "http://vignette2.wikia.nocookie.net/prehistoricmonsters/images/d/df/Raptorex_i_protarachaeopteryx-1.jpg/revision/latest?cb=20121101225010",
  ],
  "Rhabdodon": [
    "http://bioinf3.uab.cat/dinosaures/images/stories/dinosaures/img/pararhabdodon.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/5/5f/Zalmoxes_shqiperorum.jpg",
    "https://farm5.staticflickr.com/4006/4314753144_75340c50c2.jpg",
  ],
  "Rhamphor": [
    "http://www.minizoo.com.au/product_images/y/103/300329__80869_zoom.png",
    "https://www.q-files.com/images/pages/galleries/633/rhamphorhynchus-5.jpg",
    "http://img.poptower.com/pic-60936/dinosaur-revolution.jpg?d=1024",
  ],
  "Rhoetosaurus": [
    "http://www.3dfx.ch/gallery/d/53320-2/Rugen+Dinosaur+Park+Greeting+Rhoetosaurus+Entrance.jpg",
    "http://www.conceptart.org/forums/attachment.php?attachmentid=1078114&stc=1&d=1286491998",
    "http://fc01.deviantart.net/fs4/i/2004/201/2/e/Rhoetosaurus_brownei___03.jpg",
  ],
  "Rugops": [
    "http://img3.wikia.nocookie.net/__cb20120818152225/dinosaurs/images/0/04/Rugops.jpg",
    "http://img1.wikia.nocookie.net/__cb20140209202748/prehistrico/es/images/e/e4/RugopsSK.jpg",
    "http://fc03.deviantart.net/fs70/i/2013/172/0/9/rugops_on_the_hunt__by_teddyblackbear2040-d6a3pol.jpg",
  ],
  "Rutiodon": [
    "http://upload.wikimedia.org/wikipedia/commons/d/da/Rutiodon_validus_21DB.jpg",
    "http://36.media.tumblr.com/tumblr_mcm90tuAMU1r38ji3o1_1280.jpg",
    "https://c2.staticflickr.com/6/5228/5845044353_f947035c68_b.jpg",
  ],
  "Saltasaurus": [
    "http://img.jeuxetjouetsenfolie.fr/pictures/products/4600_4699/4666_0_1600x1200_386b628512f0301695ff909c1efd85ae475d1d39.jpg",
    "http://www.eng.naturaliter.com/wp-content/uploads/2011/10/saltasaurus12m2.jpg",
    "http://www.tunturisusi.com/dinosaurukset/saltasaurus3.jpg",
  ],
  "Saltriosaurus": [
    "http://img2.wikia.nocookie.net/__cb20140911125800/dinosaurs/images/7/7f/Parco_della_Preistoria_Saltriosaurus.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/a/a5/Carcharodontosaurus_BW.jpg",
    "http://www.wikidino.com/wp-content/uploads/St.GeorgeTheropodcolor-Brett-Booth.jpg",
  ],
  "Sarcosuchus": [
    "http://upload.wikimedia.org/wikipedia/commons/d/d7/Dinosaurios_Park,_Sarcosuchus.JPG",
    "http://images4.fanpop.com/image/photos/23700000/Sarcosuchus-dinosaurs-23743587-800-410.jpg",
    "http://vignette2.wikia.nocookie.net/planetdinosaur/images/7/7d/1x1_SarcosuchusScaresOffSpinosaurus.png/revision/latest?cb=20140202110043",
  ],
  "Seismosaurus": [
    "http://www.columbia.edu/dlc/cup/gillette/gillette19ab.gif",
    "http://fc01.deviantart.net/fs70/i/2011/164/e/b/seismosaurus_by_citizen1987-d3is9sr.jpg",
    "http://www.columbia.edu/dlc/cup/gillette/gillette16ab.gif",
  ],
  "Sharovipteryx": [
    "http://img4.wikia.nocookie.net/__cb20110819220906/adventuretimewithfinnandjake/images/f/fe/Sharovipteryx.png",
    "http://upload.wikimedia.org/wikipedia/commons/b/b8/Sharovipteryx.jpg",
    "http://36.media.tumblr.com/508f2081dde97df340a1a318b2f5d89b/tumblr_nd0tylWrQo1s3yrubo1_1280.jpg",
  ],
  "Shuvuuia": [
    "http://fc07.deviantart.net/fs71/f/2011/097/b/7/shuvuuia_deserti_old_version_by_steveoc86-d3dffbg.jpg",
    "http://www.luisrey.ndtilda.co.uk/jpegs/256col/Psittac1.jpg",
    "http://fc00.deviantart.net/fs70/i/2012/212/4/7/shuvuuia_deserti_by_malvit-d59bey3.jpg",
  ],
  "Silurian": [
    "http://period6timeperiods.wikispaces.com/file/view/silurian-fragment_WEB.jpg/212210808/silurian-fragment_WEB.jpg",
    "http://clccharter.org/clayton1/Silurian%20preiod/I10-29-Silurian.jpg",
    "http://i.livescience.com/images/i/000/053/959/iFF/silurian-sea-life.jpg?1371692268",
    "http://ichef.bbci.co.uk/naturelibrary/images/ic/credit/640x395/s/si/silurian/silurian_1.jpg",
    "http://www.search4dinosaurs.com/Silurian-Sea-Scorpians-New-York.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/1/13/Silurian_flora.JPG",
  ],
  "Sinornithosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/a/a9/Sinornithosaurus.jpg",
    "http://i.ytimg.com/vi/8-jpuywa6lg/maxresdefault.jpg",
    "http://www.zdf.de/ZDF/zdfportal/blob/23102210/2/data.jpg",
  ],
  "Sinosauropterx": [
    "http://fc07.deviantart.net/fs70/i/2011/070/7/8/sinosauropteryx_by_baryonyx_walkeri-d3bes7j.jpg",
    "http://fc04.deviantart.net/fs70/f/2011/213/0/a/sinosauropteryx_by_jeremyk9-d42eo1n.jpg",
    "http://fc00.deviantart.net/fs51/f/2009/325/4/6/Sinosauropteryx_by_PWNZ3R_Dragon.png",
  ],
  "Spinosaurus": [
    "http://i.telegraph.co.uk/multimedia/archive/03035/spinosaurus_3035774k.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/b/b3/Spinosaurus_Tierpark_Germendorf.jpg",
    "http://vignette1.wikia.nocookie.net/walkingwith/images/a/aa/SpinosaurusInfobox.png/revision/latest?cb=20131217214946",
  ],
  "Staurikosaurus": [
    "http://img4.wikia.nocookie.net/__cb20130413201833/dinosaurs/images/5/5b/9_The_Sound2.jpg",
    "http://classconnection.s3.amazonaws.com/61/flashcards/1316061/png/staurikosaurus1335383964478.png",
    "http://animalreader.ru/wp-content/uploads/2014/09/Staurikosaurus.jpg",
  ],
  "Stegosaurus": [
    "http://img2.wikia.nocookie.net/__cb20140811155549/dinosaurs/images/f/f9/Stegosaurus-shutterstock.jpg",
    "http://preview.turbosquid.com/Preview/2014/08/08__18_10_53/StegosaurusRigged_390.jpga20e6b16-28ef-436a-ac4b-a18b9b0ff6acOriginal.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/6/61/Dinosaurios_Park,_Stegosaurus_young.JPG",
  ],
  "Streptospondylus": [
    "http://upload.wikimedia.org/wikipedia/commons/6/6d/Metriacanthosaurus.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/e/e5/Segno.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/d/d1/Piveteausaurus_divesensis_jmallon.jpg",
  ],
  "Stygimoluch": [
    "http://fc04.deviantart.net/fs71/i/2012/081/6/b/stygimoloch_by_baryonyx_walkeri-d4tldnh.jpg",
    "http://gregmansfield.com/Photos/Spring2011/Images/g3260130-1.jpg",
    "http://fc02.deviantart.net/fs71/i/2013/105/e/e/stygimoloch_done_4_by_blade_of_the_moon-d61w09h.jpg",
  ],
  "Styracosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/c/ce/Styracosaurus_Baltow_20051003_1315.jpg",
    "https://thedinosaurboy.files.wordpress.com/2012/11/styracosaurus.jpg",
    "http://dinosaurios.org/wp-content/uploads/2013/09/DaspletosaurusandStyracosaurus.jpg",
  ],
  "Tapejara": [
    "https://spinokingtech104.files.wordpress.com/2013/02/tapejara_body1.jpg",
    "http://plesiosauria.com/dinotoyimage/sept09/tapejara_safari4.jpg",
    "http://img1.wikia.nocookie.net/__cb20110824192455/adventuretimewithfinnandjake/images/f/f6/Tapejara.jpg",
  ],
  "Tarbosaurus": [
    "http://www.nhm.ac.uk/resources/nature-online/life/dinosaurs/dinosaur-directory/images%5Creconstruction/large/tarbosaurus-eframovi.jpg",
    "http://dinosaurios.org/wp-content/uploads/2013/08/tarbosaurus_by_ministerart.jpg",
    "http://i.ytimg.com/vi/6aBAaeuQcwE/maxresdefault.jpg",
  ],
  "Tenontosaurus": [
    "http://vignette4.wikia.nocookie.net/monstersresurrected/images/6/67/Tenontosaurus.jpg/revision/latest?cb=20110817233856",
    "http://www.dinocasts.com/images/products/Tenontosaurus%205.jpg",
    "http://www.dinocasts.com/images/products/Tenontosaurus%202b.jpg",
  ],
  "Torosaurus": [
    "http://upload.wikimedia.org/wikipedia/commons/9/95/Torosaurus_BW.jpg",
    "http://www.search4dinosaurs.com/gooday/Torosaurus.jpg",
    "http://vignette1.wikia.nocookie.net/walkingwithdinos/images/b/bd/Image11c.jpg/revision/latest?cb=20110430130820",
  ],
  "Triassic": [
    "http://www.weekendnotes.com/im/006/04/triassic-canning-vale-dinosaurs-play-centre-triass1.JPG",
    "http://41.media.tumblr.com/tumblr_lyov7i84sq1qc6j5yo1_1280.jpg",
    "http://clccharter.org/christian1/triassic/BrusatteTriassicScene.gif",
  ],
  "Triceratops": [
    "http://www.wesleym.info/finalproject/wp-content/uploads/2012/11/Triceratops_BW.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/c/c7/Triceratops_-_JuraPark_Baltow.JPG",
    "http://dinosaurios.org/wp-content/uploads/2013/07/triceratops.jpg",
  ],
  "Tylosaurus": [
    "http://vignette3.wikia.nocookie.net/walkingwith/images/c/c1/TylosaurusMain.png/revision/latest?cb=20131116090938",
    "http://fc06.deviantart.net/fs70/i/2013/209/f/d/tylosaurus_riapaeus_by_malvit-d6fel9a.jpg",
    "http://media.moddb.com/images/games/1/13/12727/tylosaurus_rend1.jpg",
  ],
  "Tyrannosaurus": [
    "http://img3.wikia.nocookie.net/__cb20131014174305/dinosaurs/images/3/32/Tyrannosaur-dino-large.png",
    "http://upload.wikimedia.org/wikipedia/commons/6/6f/Feathered_Tyrannosaurus_model.jpg",
    "http://th05.deviantart.net/fs71/PRE/i/2013/214/8/e/tyrannosaurus_rex_by_fordgt-d6ge0ci.jpg",
  ],
  "Valdosaurus": [
    "http://images.fineartamerica.com/images-medium-large/dryosaurus-altus-prehistoric-era-sergey-krasovskiy.jpg",
    "http://wightpod.co.uk/wp-content/uploads/2013/04/Dino-3-Compton-web-only.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/b/b0/Dryosaurus_lettowvorbecki_skeleton.jpg",
  ],
  "Velociraptor": [
    "http://img1.wikia.nocookie.net/__cb20120928165731/jurassicpark/images/3/39/Tumblr_maitioGBUI1qhsdu1o3_1280.jpg",
    "http://cornucopia3d.e-oncontent.com/storeItems/Objects/Animals/Prehistoric/Velociraptor_Vue_3_0_img.jpg",
    "http://screeninvasion.com/wp-content/uploads/2013/06/jurassic-park-velociraptor.jpg",
  ],
  "Ventastega": [
    "http://upload.wikimedia.org/wikipedia/commons/4/45/Limnoscelis21DB.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/b/b5/Ventastega_BW.jpg",
    "http://fc08.deviantart.net/fs70/i/2010/168/c/5/Ventastega_by_Kahless28.jpg",
  ],
  "Wuerhosaurus": [
    "http://img4.wikia.nocookie.net/__cb20130217223354/dinosaurs/images/e/ed/Wuerhosaurus2.jpg",
    "http://s.hswstatic.com/gif/dinosaur-images-074-resize.jpg",
    "http://upload.wikimedia.org/wikipedia/commons/e/e5/Wuerhosaurus.jpg",
    "http://www.wikidino.com/wp-content/uploads/Wuerhosaurus-Tuomas-Koivurinne-600x417.png",
  ],
  "Xuanhanosaurus": [
    "http://img3.wikia.nocookie.net/__cb20130624170852/dinosaurs/images/6/60/Xuanhanosaurus-1.jpg",
    "http://i53.photobucket.com/albums/g62/TigerQuoll/dinosaur/torvosaurus-illustration_zps31601d17.jpg",
    "http://img3.wikia.nocookie.net/__cb20130610203345/dinosaurs/images/8/85/Apatodon.jpg",
  ],
  "Yangchuanosaurus": [
    "http://www.rareresource.com/photos/Yangchuanosaurus.jpg",
    "http://images.fineartamerica.com/images-medium-large/yangchuanosaurus-shangiouensis-sergey-krasovskiy.jpg",
    "http://fc03.deviantart.net/fs71/f/2011/343/3/a/3ae76aa39a0987e963bc1ca1958d293a-d4i65ku.jpg",
  ],
  "Zuniceratops": [
   "http://upload.wikimedia.org/wikipedia/commons/5/51/Zuniceratops_BW.jpg",
   "http://www.search4dinosaurs.com/zuniceratops.jpg",
   "http://posercontent.com/sites/default/files/products/140413/1842/zuniceratops-for-daz-studio-1.jpg",
   "http://www.arcadiastreet.com/cgvistas/earth/03_mesozoic/images/zuniceratops_portrait_600.jpg",
   "http://www.rareresource.com/photos/dinosaur-gallery/zuniceratops11.jpg",
   "http://www.rareresource.com/photos/dinosaur-gallery/zuniceratopse.jpg",
 ]
}
